# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "17:00"
#     target-branch: "dev"
#     labels:
#       - "external-dependency"